version: '3'

tasks:
  format:
    cmds:
      - ocamlformat --inplace ./src/**/*.ml
      - ocamlformat --inplace ./src/*.ml
      - ocamlformat --inplace ./bin/*.ml
      - ocamlformat --inplace ./test/*.ml

      - ocamlformat --inplace ./src/**/*.mli
      - ocamlformat --inplace ./src/*.mli
    silent: false
    aliases:
      - f
  run:
    dir: .
    cmds:
      - dune exec bin/main.exe {{.CLI_ARGS}}
    silent: false
    aliases:
      - r
  test:
    dir: .
    cmds:
      - PROJECT_ROOT=`pwd` dune test
    silent: false
    aliases:
      - t
  precommit:
    dir: .
    cmds:
      - task: test
      - task: format
    silent: false
    aliases:
      - p
